2019-12-24-issuing/config/routes.rb
Rails.application.routes.draw do
  root 'cardholders#index'
  resources :cardholders
  resources :cards
  resources :webhooks
end

2019-12-24-issuing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

2019-12-24-issuing/app/controllers/cardholders_controller.rb
class CardholdersController < ApplicationController
  def index
    @cardholders = Stripe::Issuing::Cardholder.list
  end

  def new
  end

  def create
    name = "#{params[:first_name]} #{params[:last_name]}"
    cardholder = Stripe::Issuing::Cardholder.create({
      status: 'active',
      type: 'individual',
      email: params[:email],
      name: name,
      billing: {
        name: name,
        address: {
          line1: params[:line1],
          city: params[:city],
          state: params[:state],
          postal_code: params[:postal_code],
          country: 'US',
        },
      },
    })
    redirect_to cardholder_path(cardholder.id)
  end

  def show
    # /cardholders/ich_xxx
    @cardholder = Stripe::Issuing::Cardholder.retrieve(params[:id])
    @cards = Stripe::Issuing::Card.list(cardholder: params[:id])
  end
end

2019-12-24-issuing/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @card = Stripe::Issuing::Card.details(params[:id])
    @transactions = Stripe::Issuing::Transaction.list(card: params[:id])
  end

  def create
    card = Stripe::Issuing::Card.create({
      cardholder: params[:cardholder],
      type: 'virtual',
      currency: 'usd',
      status: 'active',
    })
    redirect_back(fallback_location: "/")
  end
end

2019-12-24-issuing/app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    event = Stripe::Event.construct_from(
      JSON.parse(request.body.read, symobolize_names: true)
    )
    case event.type
    when 'issuing_authorization.request'
      # approve or decline
      authorization = event.data.object

      if authorization.pending_authorized_amount <= 5000
        Stripe::Issuing::Authorization.approve(authorization.id, {
          metadata: { reason: "less than or equal $50" }
        })
      else
        Stripe::Issuing::Authorization.decline(authorization.id, {
          metadata: { reason: "more than $50" }
        })
      end
    end

    render json: { message: "success" }
  end
end

2019-12-24-issuing/app/helpers/cardholders_helper.rb
module CardholdersHelper
end

2019-12-24-issuing/app/helpers/cards_helper.rb
module CardsHelper
end

2019-12-24-issuing/app/views/cardholders/index.html.erb
<h1>Cardholders</h1>

<a href="/cardholders/new">Add Cardholder</a>

<ul>
  <% @cardholders.each do |cardholder| %>
  <li><%= link_to "#{cardholder.id} #{cardholder.name}", cardholder_path(cardholder.id) %></li>
  <% end %>
</ul>

2019-12-24-issuing/app/views/cardholders/new.html.erb
<h1>Cardholders</h1>

<form action="/cardholders" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <fieldset>
    <label>
      <span>First Name</span>
      <input type="text" name="first_name" id="" value="">
    </label>

    <label>
      <span>Last Name</span>
      <input type="text" name="last_name" id="last_name" value="" class="field">
    </label>
    <label>
      <span>Email</span>
      <input type="text" name="email" id="email" value="" class="field">
    </label>
    <label>
      <span>Line1</span>
      <input type="text" name="line1" id="line1" value="" class="field">
    </label>
    <label>
      <span>City</span>
      <input type="text" name="city" id="city" value="" class="field">
    </label>
    <label>
      <span>State</span>
      <input type="text" name="state" id="state" value="" class="field">
    </label>
    <label>
      <span>Postal Code</span>
      <input type="text" name="postal_code" id="postal_code" value="" class="field">
    </label>
  </fieldset>

  <button>Create Cardholder</button>
</form>

2019-12-24-issuing/app/views/cardholders/show.html.erb
<h1><%= @cardholder.name %></h1>

<hr>

<h3>Cards</h3>

<form action="/cards" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="cardholder" value="<%= params[:id] %>">
  <button>Create Card</button>
</form>

<ul>
  <% @cards.each do |card| %>
  <li><%= link_to card.id, card_path(card.id) %></li>
  <% end %>
</ul>


<hr>

<pre class="code">
  <%= @cardholder %>
</pre>

2019-12-24-issuing/app/views/cards/show.html.erb
<h1>Cards</h1>

<p>Card Number: <%= @card.number %></p>
<p>Card Expiration: <%= @card.exp_month %>/<%= @card.exp_year %></p>
<p>Card CVC: <%= @card.cvc %></p>

<hr>

<h3>Transactions</h3>

<table>
  <tr>
    <th>ID</th>
    <th>Amount</th>
    <th>Merchant</th>
  </tr>
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.id %></td>
      <td><%= transaction.amount %></td>
      <td><%= transaction.merchant_data.name %></td>
    </tr>
  <% end %>
</table>

<hr>

<pre class="code">
  <%= @card %>
</pre>

2019-12-24-issuing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IssuingDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stripe-samples.github.io/developer-office-hours/demo.css" type="text/css" />
  </head>

  <body>
    <div id="main">
      <div id="checkout">
        <div id="payment-form">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>